"""
Extract the embedded (encoded bytecode, charset) pair from a Hercules-obfuscated
Lua source file.

Hercules wraps the obfuscated payload in a runtime stub generated by
`VMGenerator.lua`. The relevant output line is:

    WrapState(BcToState('<encoded>','<charset>'),(getfenv and getfenv(0)) or _ENV)()

After variable-renaming, `WrapState` and `BcToState` become random identifiers,
but the surrounding structure is preserved. We use a tolerant search to locate
the call and capture both string literals.

Decoding pipeline (mirrors `VMStrings.lua`):

    1. The `<charset>` string is a sequence of `\\NN` escapes — one byte per
       escape. It defines a base-N alphabet (N = len(charset)).
    2. The `<encoded>` string is similarly a sequence of `\\NN` escapes that
       decode to bytes forming the *inner* string.
    3. The inner string is split on `_` (byte 95). Each chunk is a base-N
       number whose digits are charset characters. The numeric value of each
       chunk is one byte of the original serialized bytecode stream.
    4. The serializer wrote `byte + '\\'` for each value, so the resulting
       byte stream alternates [data, '\\', data, '\\', ...]. The actual
       bytecode bytes are the even-indexed ones.

After step 4 we have the raw buffer that `deserializer.deserialize` accepts.

------------------------------------------------------------------------
WHITESPACE TOLERANCE — Hercules 2.0.0 vs 2.0.1
------------------------------------------------------------------------

The exact punctuation of the `(getfenv and getfenv(0)) or _ENV` tail differs
between versions:

    2.0.0:  ...,(getfenv and getfenv(0))or _ENV)()
    2.0.1:  ...,(getfenv and getfenv(0)) or _ENV)()

(The 2.0.1 generator inserts spaces around the `or` keyword — see
`VMGenerator.lua` line 91.)

The matcher below accepts any whitespace (including none) around both `and`
and `or`, so it correctly handles 2.0.0, 2.0.1, and likely future variants.

------------------------------------------------------------------------
CATASTROPHIC BACKTRACKING GUARD
------------------------------------------------------------------------

A naive single regex over the entire source can hang for many seconds (or
indeed indefinitely on multi-MB inputs) when the input does NOT contain a
Hercules payload. The hang happens because:

  * `\\w+\\(` is tried at every position;
  * on a partial match the engine greedily consumes `[^']*` and then has to
    backtrack one character at a time when the trailing literal
    `(getfenv and getfenv(0)) or _ENV)()` doesn't line up;
  * with many `'` chars and many start positions this is O(n^2) or worse.

We avoid this by:

  1. Cheap substring pre-checks (`_ENV`, `getfenv`, `'` must all be present).
  2. Locating the unique `_ENV)()` tail anchor first via a fast literal regex.
  3. Running the full pattern only on a bounded window ending at the anchor.
  4. Using possessive quantifiers (`[^']*+`) inside the full pattern so that
     once the inner string literals are matched they cannot be re-split by
     backtracking.

Together these make the worst-case behavior O(n) instead of O(n^2), and the
typical Hercules case is sub-millisecond even on multi-MB inputs.
"""

from __future__ import annotations
import re
import sys
from typing import Tuple, Optional

# Lift Python's default int-string conversion limit: encoded chunks can be
# arbitrarily long when the base is small (e.g., base-2 would explode).
sys.set_int_max_str_digits(2_000_000)


# ---------------------------------------------------------------------------
# Anchor: the unique `_ENV)()` tail that every Hercules payload ends with.
# We tolerate whitespace because some Hercules variants emit `_ENV) ()` etc.
# ---------------------------------------------------------------------------
_ANCHOR_RE = re.compile(r"_ENV\s*\)\s*\(\s*\)")


# ---------------------------------------------------------------------------
# Full payload pattern.
#
# Tolerances baked in:
#   * `\w+` for both the outer (WrapState) and inner (BcToState) function
#     names — variable_renamer replaces them with random identifiers.
#   * `\s+` between `getfenv` and `and` and between `and` and `getfenv(0)`
#     (always spaces in practice, but tolerant).
#   * `\s*` between `)` and `or` and between `or` and `_ENV` — this is the
#     key 2.0.0-vs-2.0.1 difference (no spaces vs. single space).
#   * `\s*` between `_ENV)` and `()` for robustness.
#
# Possessive `[^']*+` prevents the inner string captures from being re-split
# by backtracking when the trailing literal doesn't line up.
# ---------------------------------------------------------------------------
_PAYLOAD_RE = re.compile(
    r"(\w+)"                       # group 1 — outer function (WrapState, renamed)
    r"\("
    r"(\w+)"                       # group 2 — inner function (BcToState, renamed)
    r"\("
    r"'([^']*)'"                   # group 3 — encoded bytecode literal
    r","
    r"'([^']*)'"                   # group 4 — charset literal
    r"\)"
    r","
    r"\(\s*getfenv\s+and\s+getfenv\s*\(\s*0\s*\)\s*\)"   # (getfenv and getfenv(0))
    r"\s*or\s*"                     # ` or ` (2.0.1) or `or ` (2.0.0)
    r"_ENV"
    r"\s*\)"                        # close WrapState call
    r"\s*\(\s*\)"                   # invoke the returned Wrapped function
)


# Maximum bytes of source to scan backwards from the anchor when looking for
# the WrapState opening. Real Hercules payloads are <100 MB; the encoded
# bytecode string dominates. Generous bound to avoid ever truncating a real
# payload while still keeping the worst-case windowed regex fast.
_MAX_PAYLOAD_WINDOW = 256 * 1024 * 1024  # 256 MB


def _decode_backslash_string(s: str) -> bytes:
    """Decode a string of `\\NN` escapes into raw bytes.

    The obfuscator emits each byte as `\\<decimal>` with no padding, so we
    greedily consume digits following every backslash. Non-escape characters
    are kept as-is (their byte value).
    """
    out = bytearray()
    i = 0
    n = len(s)
    while i < n:
        ch = s[i]
        if ch == "\\" and i + 1 < n:
            j = i + 1
            num = ""
            while j < n and s[j].isdigit():
                num += s[j]
                j += 1
            if num:
                out.append(int(num) & 0xFF)
                i = j
                continue
        out.append(ord(ch) & 0xFF)
        i += 1
    return bytes(out)


def find_payload(src: str) -> Optional[Tuple[str, str, str, str, int]]:
    """Locate the WrapState(...) call inside `src`.

    Returns (wrap_fn_name, deser_fn_name, encoded_str, charset_str, match_pos)
    or None if no Hercules payload is found.

    This function is guaranteed to terminate in O(n) time on any input —
    see the module docstring for the catastrophic-backtracking guard.
    """
    # ---- 1. Cheap substring pre-checks ---------------------------------
    # If any of these literals is missing, no Hercules payload can be present
    # and we bail out without ever invoking the regex engine. This makes
    # non-Hercules files (other obfuscators, plain Lua, random text) return
    # in microseconds instead of hanging.
    if "_ENV" not in src:
        return None
    if "getfenv" not in src:
        return None
    if "'" not in src:
        return None

    # ---- 2. Locate the `_ENV)()` anchor --------------------------------
    anchor = _ANCHOR_RE.search(src)
    if anchor is None:
        return None
    anchor_end = anchor.end()

    # ---- 3. Run the full pattern on a bounded window -------------------
    # The payload begins somewhere before the anchor. Bound the search window
    # so the regex engine never has to scan an unbounded prefix.
    window_start = max(0, anchor_end - _MAX_PAYLOAD_WINDOW)
    window = src[window_start:anchor_end]

    m = _PAYLOAD_RE.search(window)
    if m is None:
        return None

    # Translate match position back to absolute source coordinates.
    abs_pos = window_start + m.start()
    return (m.group(1), m.group(2), m.group(3), m.group(4), abs_pos)


def decode_payload(encoded_str: str, charset_str: str) -> bytes:
    """Decode the (encoded, charset) pair into raw Hercules bytecode bytes."""
    charset_bytes = _decode_backslash_string(charset_str)
    if not charset_bytes:
        raise ValueError("Empty charset")
    base = len(charset_bytes)
    decode_lookup = {chr(charset_bytes[i]): i for i in range(base)}

    # Step 1: encoded_str -> inner byte string (the base-N text representation).
    inner = _decode_backslash_string(encoded_str).decode("latin-1")

    # Step 2: split on "_" and base-N decode each chunk to a single byte.
    raw = bytearray()
    for chunk in inner.split("_"):
        if not chunk:
            continue
        n = 0
        for ch in chunk:
            v = decode_lookup.get(ch)
            if v is None:
                raise ValueError(f"Character {ch!r} not in charset")
            n = n * base + v
        if n < 0 or n > 0xFF:
            raise ValueError(f"Decoded value {n} out of byte range")
        raw.append(n)

    # Step 3: serializer interleaved each data byte with a literal backslash.
    # Strip the backslash separators (every odd-indexed byte).
    data = bytes(raw[0::2])
    return data


def is_hercules(src: str) -> bool:
    """Quick check: does this source look like a Hercules-obfuscated file?"""
    # Watermark line from `manifest.output.watermark_text` and older versions.
    # Manifests in both 2.0.0 and 2.0.1 still emit the v2.0.0 watermark text
    # by default, so we accept either version marker.
    #
    # The watermark sits AFTER the standard Lua 5.3+ / Luau compatibility
    # polyfills (which are ~440 bytes), so we need to scan at least the first
    # 1 KiB to catch it. We scan 2 KiB to be safe (some polyfill variants
    # are slightly longer).
    head = src[:2048]
    if "Hercules" in head and "Obfuscated by" in head:
        return True
    # Fallback: detect the runtime payload. find_payload is O(n) and safe.
    if find_payload(src) is not None:
        return True
    # Hercules 2.0.0/2.0.1 BytecodeEncoder format (used when the
    # `bytecode_encoding` module is enabled without the VirtualMachine).
    if find_bytecode_encoder_payload(src) is not None:
        return True
    return False


# ---------------------------------------------------------------------------
# Hercules BytecodeEncoder payload (Lua 5.4 native bytecode, hex-XOR wrapped)
#
# The `bytecode_encoder` module (src/modules/bytecode_encoder.lua) emits:
#
#     local e, o, d = "<hex>", <offset>, {}
#     for i = 1, #e, 2 do
#         local b = tonumber(e:sub(i, i + 1), 16)
#         b = (b - o + 256) % 256
#         d[#d + 1] = string.char(b)
#     end
#     local f = assert(load(table.concat(d)))
#     f()
#
# Where:
#   * `<hex>` is a hex-encoded dump of `string.dump(load(source))`, each byte
#     shifted by `<offset>` mod 256.
#   * `<offset>` is a random integer in [1, 255].
#
# Decoding: for each hex pair, parse to int, subtract offset (mod 256), and
# the resulting byte is part of a standard Lua 5.4 binary chunk.
# ---------------------------------------------------------------------------
import re as _re

_BYTECODE_ENCODER_RE = _re.compile(
    r'local\s+e\s*,\s*o\s*,\s*d\s*=\s*"'
    r'([0-9A-Fa-f]+)'          # group 1: hex-encoded bytecode
    r'"\s*,\s*'
    r'(\d+)'                    # group 2: offset
    r'\s*,\s*\{\s*\}'
)


def find_bytecode_encoder_payload(src: str) -> Optional[Tuple[str, int, int]]:
    """Locate the Hercules BytecodeEncoder stub inside `src`.

    Returns (hex_str, offset, match_pos) or None if no BytecodeEncoder
    payload is found. The hex string is the obfuscated bytecode dump; the
    offset is the per-byte XOR-ish shift applied during encoding.
    """
    # Cheap pre-check: the encoder stub always contains the tell-tale
    # `tonumber(e:sub(i, i + 1), 16)` substring.
    if "tonumber(e:sub" not in src:
        return None
    m = _BYTECODE_ENCODER_RE.search(src)
    if m is None:
        return None
    return (m.group(1), int(m.group(2)), m.start())


def decode_bytecode_encoder(hex_str: str, offset: int) -> bytes:
    """Decode the (hex, offset) pair from BytecodeEncoder into raw Lua 5.4
    bytecode bytes.

    Each hex pair is one byte value; subtract `offset` mod 256 to recover
    the original byte. The resulting byte stream is a standard Lua 5.4
    binary chunk suitable for `lua54_bytecode.parse()`.
    """
    if len(hex_str) % 2 != 0:
        raise ValueError("Hex string has odd length")
    raw = bytearray()
    for i in range(0, len(hex_str), 2):
        b = int(hex_str[i:i+2], 16)
        raw.append((b - offset) % 256)
    return bytes(raw)
